open! Core
open! Async

(* convert: xml → org + rss ============================================ *)

let convert_command =
  Command.async
    ~summary:"Convert a CWN XML file into org-mode and RSS files."
    (let%map_open.Command file = anon ("FILE" %: string)
     and japanese =
       flag
         "-japanese"
         no_arg
         ~doc:" emit Japanese boilerplate, nav links, and RSS URLs"
     in
     fun () ->
       let language =
         match japanese with
         | true -> Language.Japanese
         | false -> English
       in
       let%bind contents = Reader.file_contents file in
       let cwn = Xmltree.of_string contents |> Cwn.of_xmltree in
       let base, _ext = Filename.split_extension file in
       let%bind () =
         Writer.save (base ^ ".org") ~contents:(Cwn.to_orgmode ~language cwn)
       in
       Writer.save (base ^ ".rss") ~contents:(Cwn.to_rss ~language cwn))
;;

(* gen-* subcommands: invoked from dune rules ========================== *)

let dates_in_dir ~dir ~ext =
  let suffix = "." ^ ext in
  let%map files = Sys.ls_dir dir in
  List.filter_map files ~f:(fun f ->
    match String.is_suffix f ~suffix with
    | true -> Cwn_date.of_filename f
    | false -> None)
;;

let gen_index_command =
  Command.async
    ~summary:"Scan DIR for *.html and emit ja/index.html to stdout."
    (let%map_open.Command dir = anon (maybe_with_default "." ("DIR" %: string)) in
     fun () ->
       let%map dates = dates_in_dir ~dir ~ext:"html" in
       print_string (Index_page.to_html ~dates))
;;

let gen_cwn_rss_command =
  let xml_decl_re = Re.compile (Re.Perl.re {|^<\?xml[^?]*\?>\s*|}) in
  Command.async
    ~summary:"Wrap the 10 most-recent ja/*.rss fragments in the channel envelope."
    (let%map_open.Command dir = anon (maybe_with_default "." ("DIR" %: string)) in
     fun () ->
       let%bind dates = dates_in_dir ~dir ~ext:"rss" in
       let%map items =
         List.sort dates ~compare:Date.descending
         |> Fn.flip List.take 10
         |> List.map ~f:(fun d ->
           Filename.concat dir [%string "%{d#Cwn_date}.rss"])
         |> Deferred.List.map ~how:`Sequential ~f:(fun path ->
           let%map raw = Reader.file_contents path in
           Re.replace_string xml_decl_re ~by:"" raw |> String.rstrip)
       in
       print_string (Cwn_rss.to_xml ~items))
;;

(* gen-dune-inc: emit per-date + aggregator rules to stdout ============ *)

(* Helper: emit a literal dune action variable like [%{exe:foo}] without
   colliding with the [%string] interpolation syntax. *)
let v name = "%{" ^ name ^ "}"

let per_date_rules date =
  let date_str = Cwn_date.to_string date in
  [%string
    {|
(rule
 (deps %{date_str}.xml)
 (targets %{date_str}.org %{date_str}.rss)
 (mode promote)
 (action
  (run %{v "exe:../bin/cwn_ja.exe"} convert -japanese %{v ("dep:" ^ date_str ^ ".xml")})))

(rule
 (deps %{date_str}.org ../scripts/org-export.el)
 (target %{date_str}.html)
 (mode promote)
 (action
  (with-stdout-to %{v "target"}
   (run emacs --batch -l ../scripts/org-export.el --visit %{v ("dep:" ^ date_str ^ ".org")}
        --eval "(princ (org-export-as 'html))" --kill))))
|}]
;;

let aggregator_rules ~html_files ~rss_files =
  [%string
    {|
(rule
 (deps %{html_files})
 (target index.html)
 (mode promote)
 (action
  (with-stdout-to %{v "target"}
   (run %{v "exe:../bin/cwn_ja.exe"} gen-index))))

(rule
 (deps %{rss_files})
 (target cwn.rss)
 (mode promote)
 (action
  (with-stdout-to %{v "target"}
   (run %{v "exe:../bin/cwn_ja.exe"} gen-cwn-rss))))

(alias
 (name default)
 (deps %{html_files} index.html cwn.rss))
|}]
;;

let gen_dune_inc_command =
  Command.async
    ~summary:"Emit ja/dune.inc — per-date build rules + aggregator rules."
    (let%map_open.Command dir = anon (maybe_with_default "." ("DIR" %: string)) in
     fun () ->
       let%map dates = dates_in_dir ~dir ~ext:"xml" in
       let dates = List.sort dates ~compare:Date.compare in
       print_endline ";; Generated by `cwn_ja gen-dune-inc` — do not edit by hand.";
       print_endline ";; Regenerate by running `dune build` (the rule in ja/dune is auto-promoted).";
       List.iter dates ~f:(fun date -> print_string (per_date_rules date));
       let files_for_ext ext =
         List.map dates ~f:(fun d -> [%string "%{d#Cwn_date}.%{ext}"])
         |> String.concat ~sep:" "
       in
       print_string
         (aggregator_rules
            ~html_files:(files_for_ext "html")
            ~rss_files:(files_for_ext "rss")))
;;

(* translate: OpenRouter-driven translation ============================ *)

(* OpenRouter model ids are "<provider>/<model>". Override via OPENROUTER_MODEL. *)
let default_model = "anthropic/claude-sonnet-4.6"

let getenv_or_error name =
  Sys.getenv name
  |> Result.of_option
       ~error:
         (Error.create_s [%message "environment variable not set" ~_:(name : string)])
;;

let translate_one ~api_key ~model ~system_prompt ~ja_dir ~cwn_data_dir date =
  let date_str = Cwn_date.to_string date in
  [%log.global.info "translating" (date : Date.t)];
  let input = Filename.concat cwn_data_dir [%string "%{date_str}.xml"] in
  let output = Filename.concat ja_dir [%string "%{date_str}.xml"] in
  let%bind content = Reader.file_contents input in
  match%bind Translator.translate ~api_key ~model ~system_prompt ~content with
  | Error err ->
    [%log.global.error "translation failed" (date : Date.t) (err : Error.t)];
    return (Error err)
  | Ok translated ->
    let%map () = Writer.save output ~contents:translated in
    Ok ()
;;

let translate_command =
  Command.async_or_error
    ~summary:"Translate cwn-data XML files to Japanese via OpenRouter."
    (let%map_open.Command file =
       flag
         "file"
         (optional Cwn_date.arg_type)
         ~doc:"DATE single date to translate (YYYY.MM.DD)"
     and since =
       flag
         "since"
         (optional Cwn_date.arg_type)
         ~doc:"DATE force-retranslate dates >= DATE"
     and from_ref =
       flag
         "from-ref"
         (optional string)
         ~doc:"REF cwn-data git ref (paired with --to-ref)"
     and to_ref =
       flag
         "to-ref"
         (optional string)
         ~doc:"REF cwn-data git ref (paired with --from-ref)"
     and prompt_path =
       flag
         "prompt"
         (optional_with_default "scripts/prompt.md" string)
         ~doc:"FILE path to system prompt (default: scripts/prompt.md)"
     and cwn_data_dir =
       flag
         "cwn-data"
         (optional_with_default "cwn-data" string)
         ~doc:"DIR upstream submodule (default: cwn-data)"
     and ja_dir =
       flag
         "ja"
         (optional_with_default "ja" string)
         ~doc:"DIR translation output (default: ja)"
     in
     fun () ->
       let open Deferred.Or_error.Let_syntax in
       let%bind api_key = Deferred.return (getenv_or_error "OPENROUTER_API_KEY") in
       let model = Option.value (Sys.getenv "OPENROUTER_MODEL") ~default:default_model in
       let%bind system_prompt =
         Monitor.try_with_or_error (fun () -> Reader.file_contents prompt_path)
       in
       let%bind dates =
         Translate_args.list_dates
           ~cwn_data_dir
           ~ja_dir
           { file; since; from_ref; to_ref }
       in
       match List.is_empty dates with
       | true ->
         [%log.global.info "no files to translate"];
         Deferred.Or_error.return ()
       | false ->
         [%log.global.info "found files to translate" (dates : Date.t list)];
         let%bind results =
           Deferred.List.map
             dates
             ~how:`Sequential
             ~f:(translate_one ~api_key ~model ~system_prompt ~ja_dir ~cwn_data_dir)
           |> Deferred.ok
         in
         let succeeded, failed = List.partition_result results in
         [%log.global.info
           "translation summary"
             ~succeeded:(List.length succeeded : int)
             ~failed:(List.length failed : int)];
         (match failed with
          | [] -> Deferred.Or_error.return ()
          | _ -> Deferred.Or_error.error_string "some translations failed"))
;;

(* top-level group ===================================================== *)

let command =
  Command.group
    ~summary:"OCaml Weekly News Japanese translation toolchain"
    [ "convert", convert_command
    ; "translate", translate_command
    ; "gen-index", gen_index_command
    ; "gen-cwn-rss", gen_cwn_rss_command
    ; "gen-dune-inc", gen_dune_inc_command
    ]
;;
