open! Core

(* convert: xml → org + rss ============================================ *)

let convert_command =
  Command.basic
    ~summary:"Convert a CWN XML file into org-mode and RSS files."
    (let%map_open.Command file = anon ("FILE" %: string)
     and japanese =
       flag
         "-japanese"
         no_arg
         ~doc:" emit Japanese boilerplate, nav links, and RSS URLs"
     in
     fun () ->
       let language : Language.t =
         match japanese with
         | true -> Japanese
         | false -> English
       in
       let cwn = Xmltree.of_file file |> Cwn.of_xmltree in
       let base, _ext = Filename.split_extension file in
       Out_channel.write_all (base ^ ".org") ~data:(Cwn.to_orgmode ~language cwn);
       Out_channel.write_all (base ^ ".rss") ~data:(Cwn.to_rss ~language cwn))
;;

(* gen-* subcommands: invoked from dune rules ========================== *)

let gen_index_command =
  Command.basic
    ~summary:"Scan DIR for *.html and emit ja/index.html to stdout."
    (let%map_open.Command dir = anon (maybe_with_default "." ("DIR" %: string)) in
     fun () ->
       let date_re = Re.compile (Re.Perl.re {|^(\d{4}\.\d{2}\.\d{2})\.html$|}) in
       let dates =
         Sys_unix.ls_dir dir
         |> List.filter_map ~f:(fun f ->
           match Re.exec_opt date_re f with
           | Some g -> Some (Re.Group.get g 1)
           | None -> None)
         |> List.sort ~compare:String.descending
       in
       print_string (Index_page.to_html ~dates))
;;

let gen_cwn_rss_command =
  let max_items = 10 in
  let date_re = Re.compile (Re.Perl.re {|^\d{4}\.\d{2}\.\d{2}\.rss$|}) in
  let xml_decl_re = Re.compile (Re.Perl.re {|^<\?xml[^?]*\?>\s*|}) in
  Command.basic
    ~summary:"Wrap the 10 most-recent ja/*.rss fragments in the channel envelope."
    (let%map_open.Command dir = anon (maybe_with_default "." ("DIR" %: string)) in
     fun () ->
       let fragments =
         Sys_unix.ls_dir dir
         |> List.filter ~f:(Re.execp date_re)
         |> List.sort ~compare:String.descending
         |> Fn.flip List.take max_items
       in
       let items =
         List.map fragments ~f:(fun f ->
           In_channel.read_all (Filename.concat dir f)
           |> Re.replace_string xml_decl_re ~by:""
           |> String.rstrip)
       in
       print_string (Cwn_rss.to_xml ~items))
;;

(* gen-dune-inc: emit per-date + aggregator rules to stdout ============ *)

let date_xml_re = Re.compile (Re.Perl.re {|^(\d{4}\.\d{2}\.\d{2})\.xml$|})

(* Helper: emit a literal dune action variable like [%{exe:foo}] without
   colliding with the [%string] interpolation syntax. *)
let v name = "%{" ^ name ^ "}"

let per_date_rules date =
  [%string
    {|
(rule
 (deps %{date}.xml)
 (targets %{date}.org %{date}.rss)
 (mode promote)
 (action
  (run %{v "exe:../bin/cwn_ja.exe"} convert -japanese %{v ("dep:" ^ date ^ ".xml")})))

(rule
 (deps %{date}.org ../scripts/org-export.el)
 (target %{date}.html)
 (mode promote)
 (action
  (with-stdout-to %{v "target"}
   (run emacs --batch -l ../scripts/org-export.el --visit %{v ("dep:" ^ date ^ ".org")}
        --eval "(princ (org-export-as 'html))" --kill))))
|}]
;;

let aggregator_rules ~html_files ~rss_files =
  [%string
    {|
(rule
 (deps %{html_files})
 (target index.html)
 (mode promote)
 (action
  (with-stdout-to %{v "target"}
   (run %{v "exe:../bin/cwn_ja.exe"} gen-index))))

(rule
 (deps %{rss_files})
 (target cwn.rss)
 (mode promote)
 (action
  (with-stdout-to %{v "target"}
   (run %{v "exe:../bin/cwn_ja.exe"} gen-cwn-rss))))

(alias
 (name default)
 (deps %{html_files} index.html cwn.rss))
|}]
;;

let gen_dune_inc_command =
  Command.basic
    ~summary:"Emit ja/dune.inc — per-date build rules + aggregator rules."
    (let%map_open.Command dir = anon (maybe_with_default "." ("DIR" %: string)) in
     fun () ->
       let dates =
         Sys_unix.ls_dir dir
         |> List.filter_map ~f:(fun f ->
           match Re.exec_opt date_xml_re f with
           | Some g -> Some (Re.Group.get g 1)
           | None -> None)
         |> List.sort ~compare:String.ascending
       in
       print_endline ";; Generated by `cwn_ja gen-dune-inc` — do not edit by hand.";
       print_endline ";; Regenerate by running `dune build` (the rule in ja/dune is auto-promoted).";
       List.iter dates ~f:(fun date -> print_string (per_date_rules date));
       let html_files =
         List.map dates ~f:(fun d -> [%string "%{d}.html"]) |> String.concat ~sep:" "
       in
       let rss_files =
         List.map dates ~f:(fun d -> [%string "%{d}.rss"]) |> String.concat ~sep:" "
       in
       print_string (aggregator_rules ~html_files ~rss_files))
;;

(* translate: OpenRouter-driven translation ============================ *)

(* Lives in its own module so [open! Async] doesn't shadow [print_string],
   [Printf], etc. used in the synchronous subcommands above. *)
module Translate = struct
  open! Async

  (* OpenRouter prefixes the provider name. Default mirrors the Anthropic-direct
     default that scripts/translate.ts used (claude-sonnet-4-6); contributors
     can override via OPENROUTER_MODEL. *)
  let default_model = "anthropic/claude-sonnet-4.6"

  let getenv name =
    Sys.getenv name
    |> Result.of_option
         ~error:
           (Error.create_s
              [%message "environment variable not set" ~_:(name : string)])
  ;;

  let translate_one ~api_key ~model ~system_prompt ~ja_dir ~cwn_data_dir date =
    printf "--- Translating %s ---\n%!" date;
    let input = Filename.concat cwn_data_dir [%string "%{date}.xml"] in
    let output = Filename.concat ja_dir [%string "%{date}.xml"] in
    let%bind content = Reader.file_contents input in
    match%bind Translator.translate ~api_key ~model ~system_prompt ~content with
    | Error err ->
      eprintf "FAILED: %s\n  %s\n%!" date (Error.to_string_hum err);
      return false
    | Ok translated ->
      let%map () = Writer.save output ~contents:translated in
      true
  ;;

  let command =
    Command.async_or_error
      ~summary:"Translate cwn-data XML files to Japanese via OpenRouter."
      (let%map_open.Command file =
         flag "file" (optional string) ~doc:"DATE single date to translate (YYYY.MM.DD)"
       and since =
         flag
           "since"
           (optional string)
           ~doc:"DATE force-retranslate dates >= DATE (lexical compare)"
       and from_ref =
         flag
           "from-ref"
           (optional string)
           ~doc:"REF cwn-data git ref (paired with --to-ref)"
       and to_ref =
         flag
           "to-ref"
           (optional string)
           ~doc:"REF cwn-data git ref (paired with --from-ref)"
       and prompt_path =
         flag
           "prompt"
           (optional_with_default "scripts/prompt.md" string)
           ~doc:"FILE path to system prompt (default: scripts/prompt.md)"
       and cwn_data_dir =
         flag
           "cwn-data"
           (optional_with_default "cwn-data" string)
           ~doc:"DIR upstream submodule (default: cwn-data)"
       and ja_dir =
         flag
           "ja"
           (optional_with_default "ja" string)
           ~doc:"DIR translation output (default: ja)"
       in
       fun () ->
         let open Deferred.Or_error.Let_syntax in
         let%bind api_key = Deferred.return (getenv "OPENROUTER_API_KEY") in
         let model =
           Option.value (Sys.getenv "OPENROUTER_MODEL") ~default:default_model
         in
         let%bind system_prompt =
           Monitor.try_with_or_error (fun () -> Reader.file_contents prompt_path)
         in
         let%bind dates =
           Source_set.list_dates
             ~cwn_data_dir
             ~ja_dir
             { file; since; from_ref; to_ref }
         in
         match List.is_empty dates with
         | true ->
           print_endline "No files to translate.";
           Deferred.Or_error.return ()
         | false ->
           printf
             "Found %d file(s) to translate: %s\n%!"
             (List.length dates)
             (String.concat ~sep:", " dates);
           let%bind succeeded, failed =
             Deferred.List.fold dates ~init:(0, 0) ~f:(fun (s, f) date ->
               Deferred.map
                 (translate_one ~api_key ~model ~system_prompt ~ja_dir ~cwn_data_dir date)
                 ~f:(function
                   | true -> s + 1, f
                   | false -> s, f + 1))
             |> Deferred.ok
           in
           printf "\nTranslation: %d succeeded, %d failed.\n%!" succeeded failed;
           (match failed with
            | 0 -> Deferred.Or_error.return ()
            | _ -> Deferred.Or_error.error_string "some translations failed"))
  ;;
end

(* top-level group ===================================================== *)

let command =
  Command.group
    ~summary:"OCaml Weekly News Japanese translation toolchain"
    [ "convert", convert_command
    ; "translate", Translate.command
    ; "gen-index", gen_index_command
    ; "gen-cwn-rss", gen_cwn_rss_command
    ; "gen-dune-inc", gen_dune_inc_command
    ]
;;
